category = {
    "Music": [
        "The song {song} is a vibe that hits hard every time.",
        "If I had to pick one song to listen to forever, it would be {song}.",
        "The energy from {artist}'s concerts is something else.",
        "Nothing boosts my mood like blasting {song} on repeat.",
        "{artist} always drops bangers, especially {song}.",
        "I discovered {song} and now it's my entire personality.",
        "Every memory from last summer is tied to {song}.",
        "You haven’t lived until you’ve heard {song} live.",
        "The lyrics of {song} hit different at 2 AM.",
        "When {artist} sings, it feels like they’re reading my soul.",
        "I swear, {song} is the soundtrack to my life.",
        "Throwbacks like {song} never get old."
    ],
    "Fun": [
        "We had the best time just {action} until we couldn't anymore.",
        "The night we {action} was legendary, I’ll never forget it.",
        "Fun is all about {activity}, nothing else matters.",
        "There’s no better feeling than {action} with your people.",
        "Spontaneous {activity} nights always hit different.",
        "Who knew {activity} could turn into a core memory?",
        "Laughed so hard while {action} that my stomach hurt.",
        "The chaos of {activity} nights is what I live for.",
        "We stayed up all night just {action}—pure vibes.",
        "{activity} might not solve everything, but it helps a lot.",
        "Nothing compares to those nights of endless {activity}.",
        "We made a mess {action}, but it was so worth it."
    ],
    "Movies": [
        "If I could be in any movie, I would totally pick {movie}.",
        "I was so hooked on {movie}, it kept me up all night.",
        "The plot in {movie} was wild, didn't see that twist coming.",
        "I lowkey cried during {movie}—don’t tell anyone.",
        "{movie} had me questioning my entire life.",
        "The cinematography in {movie} was next-level.",
        "Watched {movie} again for the 5th time, no regrets.",
        "That one line from {movie} is stuck in my head forever.",
        "I felt seen watching {movie}.",
        "If you haven’t watched {movie}, you’re missing out.",
        "The characters in {movie} felt too real.",
        "{movie} deserves an award, no cap."
    ],
    "Jokes": [
        "I told my friend a joke about {joke_subject}, and they couldn't stop laughing!",
        "Why don't skeletons fight each other? Because they don’t have the guts!",
        "How does a penguin build its house? Igloos it together!",
        "I tried a joke about {joke_subject}, and even I laughed.",
        "What did the ocean say to the beach? Nothing, it just waved.",
        "I told a joke so bad about {joke_subject}, it was actually funny.",
        "Why was the math book sad? It had too many problems.",
        "Knock knock. Who’s there? {joke_subject}. {joke_subject} who? Classic.",
        "I said a dad joke and instantly felt 30 years older.",
        "What do you call fake spaghetti? An impasta.",
        "Jokes about {joke_subject} always get a reaction.",
        "Told a joke at the wrong time... still worth it."
    ],
    "Relationships": [
        "Dating is confusing, but that’s part of the thrill of {verb}.",
        "It’s always hard to deal with rejection, but it teaches you {lesson}.",
        "Sometimes, relationships feel like {object}, fragile but worth it.",
        "Falling for someone feels like {object}—sudden and intense.",
        "The best relationships start with {action}.",
        "You learn more about yourself from every {relationship_type}.",
        "It’s wild how one person can make everything {adjective}.",
        "Ghosting sucks, but it says more about them than you.",
        "Sometimes love is just a series of {lesson}s.",
        "It’s not about perfect love, it’s about {verb} together.",
        "We were just two people trying not to {verb} things up.",
        "It ended, but I’ll always remember the {memory}."
    ],
    "Tattoos": [
        "If I get a tattoo, it’s going to represent {theme}, something personal.",
        "I’m thinking about getting a tattoo that reminds me of {memory}.",
        "Tattoos are like a permanent story, each one says {message}.",
        "I want a tattoo that screams {theme} without saying a word.",
        "Every tattoo should tell a {story}.",
        "Matching tattoos with your best friend? Iconic.",
        "A tiny tattoo that means the world to me.",
        "Still deciding if I want a tattoo of {object} or {symbol}.",
        "The idea of ink and skin feels like {emotion}.",
        "Saw a tattoo of {thing} and now I want it too.",
        "Tattoo inspiration hits hardest when you're emotional.",
        "A quote from {book} would look fire as a tattoo."
    ],
    "Life": [
        "Life’s about finding {thing} that make everything worth it.",
        "If there’s one thing I’ve learned, it’s to {verb} every moment.",
        "Life hits differently when you’re not worried about {subject}.",
        "The little things, like {object}, are what really matter.",
        "Every day is a chance to {verb} again.",
        "Life isn’t perfect, but it’s full of {lesson}s.",
        "You grow through what you {verb}.",
        "Sometimes, life just needs a reset and some {activity}.",
        "The older I get, the more I value {thing}.",
        "It’s not about the destination, it’s about the {journey}.",
        "Life without {emotion} feels empty.",
        "Gratitude changes everything, even {thing}."
    ],
    "Rizz": [
        "The key to rizz is knowing how to {action} in any situation.",
        "You can’t fake rizz, either you have it or you don’t, like {thing}.",
        "Rizz is all about being {adjective} with confidence, no second guessing.",
        "My rizz levels go up when I start talking about {topic}.",
        "The ultimate flex is silent rizz—just vibes.",
        "If you’ve got rizz, you don’t need {object}.",
        "I learned rizz from watching {character} in {movie}.",
        "Sometimes rizz is just making them laugh about {joke_subject}.",
        "Real rizz comes from being yourself, not from {thing}.",
        "One look and the rizz was activated.",
        "Even my texts have rizz when I mention {song}.",
        "The moment I mentioned {fun_fact}, I knew the rizz worked."
    ],
    "Girls": [
        "Girls have this way of making everything {adjective}, and it’s amazing.",
        "You can never predict what a girl will say, but it’s always {adjective}.",
        "Girls bring a vibe that's {adjective}, even when it’s unexpected.",
        "Talking to her felt like {song}—smooth and unforgettable.",
        "Girls notice the tiniest details, like {object}.",
        "She laughed and it sounded like {thing}.",
        "The way she said {quote} stuck with me.",
        "A girl with confidence is unstoppable.",
        "You think you’ve figured her out, then she does {action}.",
        "Every girl is a whole story, not just a chapter.",
        "Girls make the world feel {adjective}.",
        "She smiled and suddenly everything was better."
    ],
    "Sex": [
        "Sex is confusing and thrilling, kind of like {emotion}.",
        "Nobody teaches you how intense {sex_topic} can feel.",
        "It’s wild how {action} can turn into something more.",
        "Conversations about sex should be as normal as {topic}.",
        "The first time felt like {adjective} chaos.",
        "Sex isn’t just physical—it messes with your {emotion}.",
        "Sometimes it's awkward, sometimes it's fireworks.",
        "Everyone pretends to know everything, but it’s mostly {lesson}.",
        "Safe sex is way cooler than pretending nothing matters.",
        "Sex ed didn’t prepare me for the real {situation}.",
        "It’s okay not to be ready, no matter what {person} says.",
        "The weirdest part is how {thing} reminds me of it."
    ],
    "Masturbation": [
        "Nobody talks about {topic}, but we all know it’s a thing.",
        "Masturbation is the most personal version of self-care.",
        "It’s like your body saying, ‘hey, I got you.’",
        "Every time someone mentions {thing}, I get flashbacks.",
        "It’s funny how we’re all secretly doing the same thing.",
        "It’s natural, but still somehow {adjective} to talk about.",
        "The guilt afterward hits harder than {emotion}.",
        "Lowkey, it’s the best way to understand your own {body_part}.",
        "Why do we act like it’s a scandal when it’s just {verb}?",
        "It’s private until someone makes it weird with {joke_subject}.",
        "Masturbation: the one thing you can’t fail at.",
        "Sometimes it’s just stress relief. Nothing more."
    ],
    "School": [
        "School is basically a full-time job with zero pay.",
        "My brain checked out after {subject} class.",
        "The best part of school is when {teacher} doesn’t show up.",
        "Trying to stay awake during {subject} is my new talent.",
        "High school drama is more chaotic than {movie}.",
        "Group projects are just unpaid therapy sessions.",
        "Why is the bell louder than my will to live?",
        "Some days I go for the education, most days for {friend}.",
        "The school lunch mystery meat should be studied in science.",
        "Nothing teaches time management like procrastinating on {thing}.",
        "The halls are just mini runways with backpacks.",
        "The weirdest thoughts happen during math tests."
    ],
    "SocialMedia": [
        "One scroll on social media and suddenly it’s 2 AM.",
        "My screen time is longer than my attention span.",
        "I post it, delete it, then repost it—classic move.",
        "She liked my story? That’s basically a relationship.",
        "I saw {person} post it and now I want it too.",
        "It’s not real life, but it sure feels like it.",
        "The algorithm knows me better than my best friend.",
        "I only go on there to ‘check something’—2 hours later...",
        "If it’s not on my story, did it even happen?",
        "Getting a like from {crush} is peak dopamine.",
        "My feed is just chaos, memes, and occasional breakdowns.",
        "Social media turned {emotion} into a trend."
    ],
    "Sports": [
        "That moment when you score and everything goes quiet—goosebumps.",
        "Practice was pain, but the win felt worth it.",
        "Game days turn nerves into {emotion}.",
        "Every bruise has a story, and I’m proud of all of them.",
        "Winning feels like {song} playing in slow motion.",
        "Lost the game, but gained a story worth telling.",
        "Sometimes the best plays happen off the field.",
        "I suck at sports, but I love the chaos.",
        "When you're in the zone, it’s just you and the {object}.",
        "Sports taught me more than any classroom ever did.",
        "The team is basically my second family.",
        "Even the losses teach you something deeper."
    ],
    "Drugs": [
        "Everyone acts chill about it, but it’s never just ‘trying’ {thing}.",
        "The first time felt like flying, until it didn’t.",
        "It’s all jokes until someone gets too deep.",
        "Some nights blur into a haze of {emotion} and regrets.",
        "Drugs feel like shortcuts to {emotion}, but it never lasts.",
        "I saw someone lose themselves to {substance}—never again.",
        "Not judging, but I’ve seen what it does to {person}.",
        "They say it’s just {drug}, but I’ve seen it change people.",
        "The high doesn’t fix what’s broken—it just hides it.",
        "Everyone has their reason. Mine was just {excuse}.",
        "You chase a feeling and lose a piece of yourself.",
        "It’s easy to start, but getting out is something else."
    ],
    "Parties": [
        "That one party changed everything for better or worse.",
        "I showed up late and still managed to be the chaos.",
        "Someone brought {object}, and everything got weird fast.",
        "Every party has that one unforgettable moment.",
        "Parties are where you find stories, not just fun.",
        "Nothing good happens after 2 AM—but I still stay.",
        "That night felt like a movie, until it didn't.",
        "I danced like no one was watching—until they did.",
        "The playlist was trash, but the vibe was {adjective}.",
        "Random people, loud music, and memories I half-remember.",
        "It started with a drink and ended with {thing}.",
        "Parties: where strangers become memories and crushes get complicated."
    ]
}
