random_replacements = {
    "song": [
        "Blinding Lights",
        "Bad Habit",
        "Montero",
        "As It Was",
        "Stay",
        "good 4 u",
        "Peaches",
        "Levitating",
        "Industry Baby",
        "drivers license",
        "Circles",
        "Sicko Mode",
        "Sunflower",
        "Lucid Dreams",
        "Happier Than Ever",
        "Midnight City",
        "Riptide",
        "Heat Waves",
        "Sweater Weather",
        "Die For You",
        "Golden Hour",
        "Shivers",
        "Adore You",
        "Can’t Hold Us",
        "Talk",
        "Goosebumps",
    ],
    "artist": [
        "Drake",
        "Billie Eilish",
        "Travis Scott",
        "Ariana Grande",
        "The Weeknd",
        "Tyler, The Creator",
        "Doja Cat",
        "Olivia Rodrigo",
        "Post Malone",
        "Kendrick Lamar",
        "Playboi Carti",
        "Lana Del Rey",
        "Lil Nas X",
        "SZA",
        "Ice Spice",
        "Tate McRae",
        "Frank Ocean",
        "Halsey",
        "Troye Sivan",
        "Steve Lacy",
        "Lil Uzi Vert",
        "Phoebe Bridgers",
        "Joji",
        "21 Savage",
        "Rihanna",
        "BLACKPINK",
    ],
    "movie": [
        "Spider-Man: No Way Home",
        "Everything Everywhere All At Once",
        "The Batman",
        "Avatar: The Way of Water",
        "Dune",
        "Oppenheimer",
        "Barbie",
        "Get Out",
        "Her",
        "Interstellar",
        "The Matrix",
        "Inception",
        "Joker",
        "The Hunger Games",
        "Tenet",
        "Perks of Being a Wallflower",
        "Scott Pilgrim vs. the World",
        "The Fault in Our Stars",
        "La La Land",
        "Coraline",
        "Deadpool",
        "The Maze Runner",
        "Euphoria (okay not a movie but fits)",
        "Twilight",
        "To All the Boys I’ve Loved Before",
        "500 Days of Summer",
    ],
    "action": [
        "dancing",
        "vibing",
        "chilling",
        "laughing",
        "skating",
        "gaming",
        "daydreaming",
        "texting",
        "scrolling",
        "joking",
        "freestyling",
        "flirting",
        "ghosting",
        "napping",
        "sneaking out",
        "browsing memes",
        "cracking jokes",
        "people watching",
        "overthinking",
        "ranting",
        "making playlists",
        "vibing in silence",
        "writing lyrics",
        "posing for pics",
        "overdressing",
    ],
    "activity": [
        "watching horror movies",
        "late-night drives",
        "playing Fortnite",
        "binge-watching Netflix",
        "sneaking snacks into class",
        "laughing at dumb memes",
        "arguing over music",
        "daydreaming in class",
        "group FaceTime calls",
        "roaming Target",
        "eating ramen at midnight",
        "making TikToks",
        "skipping gym",
        "drawing tattoos in notebooks",
        "karaoke in the car",
        "going thrift shopping",
        "jumping fences",
        "singing off-key",
        "faking accents",
        "late-night baking",
        "talking in code",
        "sneaking snacks to the movies",
        "arguing over astrology",
        "writing fake bios",
        "people-watching at the mall",
    ],
    "object": [
        "a cracked phone screen",
        "a friendship bracelet",
        "a mixtape",
        "a hoodie",
        "a vinyl record",
        "a concert ticket",
        "a Snapchat streak",
        "a thrifted flannel",
        "an old diary",
        "a pair of Vans",
        "a concert wristband",
        "a fading Polaroid",
        "a playlist",
        "a lost AirPod",
        "a meme account",
        "a cracked mirror selfie",
        "a mixtape cover",
        "a half-burnt candle",
        "a scrunchie",
        "a forgotten hoodie",
        "a dried flower",
        "a chain necklace",
        "a blurry screenshot",
        "a worn-out notebook",
        "a gel pen drawing",
    ],
    "verb": [
        "embracing",
        "escaping",
        "vibing with",
        "replaying",
        "trusting",
        "ignoring",
        "romanticizing",
        "documenting",
        "ghosting",
        "snapping",
        "posting",
        "reposting",
        "obsessing over",
        "craving",
        "manifesting",
        "restarting",
        "spilling",
        "escaping",
        "reminiscing",
        "hiding",
        "linking up",
        "posting cryptic stories",
        "leaving people on read",
        "double texting",
        "playing it cool",
    ],
    "lesson": [
        "how to let go",
        "patience",
        "not everyone stays",
        "self-worth",
        "to stop overthinking",
        "it's okay to feel lost",
        "ghosting isn't the end",
        "the value of silence",
        "boundaries matter",
        "to love myself first",
        "vulnerability is strength",
        "not all vibes last",
        "that peace is priceless",
        "how to move on",
        "healing isn’t linear",
        "jealousy fades",
        "timing matters",
        "ghosting stings",
        "vibes lie",
        "closure is rare",
        "your gut knows",
        "it’s okay to cry",
        "you’re not for everyone",
        "some things are just phases",
        "don’t chase, attract",
    ],
    "theme": [
        "freedom",
        "healing",
        "chaos",
        "loyalty",
        "growth",
        "friendship",
        "first love",
        "rebellion",
        "late nights",
        "nostalgia",
        "hope",
        "trust issues",
        "cosmic vibes",
        "heartbreak",
        "ambition",
        "silence",
        "independence",
        "rebirth",
        "double meanings",
        "growing pains",
        "insecurity",
        "forgiveness",
        "vulnerability",
        "teen rage",
        "ephemeral love",
    ],
    "memory": [
        "that summer at the lake",
        "our first concert",
        "the late-night phone calls",
        "homecoming night",
        "the first time we skipped class",
        "our matching tattoos",
        "the beach at midnight",
        "crying in the school bathroom",
        "our spontaneous road trip",
        "sneaking out",
        "our Halloween costumes",
        "watching the sunrise together",
        "laughing till we cried",
        "sitting on the rooftop",
        "sharing earbuds on the bus",
        "the night we got lost",
        "our first FaceTime",
        "the time we matched outfits",
        "camping in the backyard",
        "when we climbed the roof",
        "our 3AM texts",
        "when we dyed our hair",
        "snow day chaos",
        "laughing in detention",
        "burning homework together",
    ],
    "message": [
        "you survived",
        "never settle",
        "feel it all",
        "let go",
        "you are enough",
        "don’t fake the vibe",
        "choose you",
        "stay loud",
        "protect your peace",
        "love isn’t always forever",
        "feelings are valid",
        "keep going",
        "trust your gut",
        "you’re allowed to start over",
        "stay wild",
        "this too shall pass",
        "vibe responsibly",
        "you’re the main character",
        "be loud about your joy",
        "you outgrew it for a reason",
        "choose real",
        "some endings are beginnings",
        "risk the cringe",
        "own your weird",
    ],
    "thing": [
        "sunsets",
        "overheard lyrics",
        "TikTok trends",
        "stolen hoodies",
        "random compliments",
        "inside jokes",
        "late replies",
        "a perfect playlist",
        "Snapchat memories",
        "deep convos at 2am",
        "airplane mode moments",
        "silly selfies",
        "DMs that never sent",
        "eyes that sparkle",
        "spontaneous plans",
        "group chats",
        "secret playlists",
        "unread texts",
        "timed selfies",
        "notes passed in class",
        "Spotify wrapped",
        "mood boards",
        "snap maps",
        "aesthetic folders",
        "IG drafts",
    ],
    "subject": [
        "college",
        "what others think",
        "follower counts",
        "DM drama",
        "fake friends",
        "being alone",
        "late homework",
        "our future",
        "group chats",
        "Instagram likes",
        "Snapchat scores",
        "what ifs",
        "old mistakes",
        "family pressure",
        "curfews",
        "SATs",
        "Snapchat streaks",
        "crush confusion",
        "drama club beef",
        "being ghosted",
        "pop quizzes",
        "glow-ups",
        "shifting friend groups",
        "prom pressure",
        "fake deep convos",
    ],
    "adjective": [
        "unpredictable",
        "chaotic",
        "iconic",
        "vulnerable",
        "aesthetic",
        "mysterious",
        "magnetic",
        "delicate",
        "underrated",
        "magical",
        "bold",
        "sweet",
        "unexpected",
        "wild",
        "dreamy",
        "chaotic good",
        "lowkey perfect",
        "vibey",
        "bittersweet",
        "electric",
        "emo-ish",
        "ethereal",
        "next level",
        "laid-back",
        "effortless",
    ],
    "joke_subject": [
        "dad jokes",
        "awkward silences",
        "bad puns",
        "TikTok fails",
        "teacher rants",
        "celebrity crushes",
        "math homework",
        "Zoom classes",
        "cheesy pickup lines",
        "cafeteria food",
        "gym class fails",
        "cringe texts",
        "school dances",
        "pet selfies",
        "Spotify ads",
        "mom texts",
        "crush fails",
        "yearbook quotes",
        "snoring in class",
        "zodiac drama",
        "typing noises",
        "wrong group chats",
        "accidental likes",
        "missed calls",
        "bad haircuts",
    ],
    "noun": [
        "vibe",
        "rizz",
        "energy",
        "mood",
        "situation",
        "chaos",
        "game",
        "drip",
        "talk",
        "feeling",
        "playlist",
        "story",
        "crush",
        "glow-up",
        "drama",
        "crush",
        "rizz",
        "aura",
        "drip",
        "glitch",
        "loop",
        "phase",
        "playlist energy",
        "ghost text",
        "rewind",
    ],
    "emotion": [
        "pure chaos",
        "total peace",
        "butterflies",
        "overthinking everything",
        "vibes overload",
        "a whole mood",
        "emotional whiplash",
        "lowkey joy",
        "unspoken connection",
        "nervous excitement",
        "random sadness",
        "instant regret",
        "heart-thumping energy",
        "emotional deja vu",
        "bittersweet nostalgia",
        "crushing disappointment",
        "unexpected happiness",
        "intense curiosity",
        "quiet confidence",
        "undeniable spark",
    ],
    "journey": [
        "the late-night talks that changed me",
        "the chaos before the clarity",
        "figuring things out the hard way",
        "growing through the awkward phases",
        "from not knowing to not caring",
        "a rollercoaster of trial and error",
        "stumbling into self-discovery",
        "healing one playlist at a time",
        "finding peace in weird places",
        "learning to stop overthinking",
        "the climb from heartbreak",
        "navigating through silence",
        "learning when to let go",
        "the stretch between who I was and who I’m becoming",
        "walking away from what broke me",
    ],
    "book": [
        "The Perks of Being a Wallflower",
        "It Ends With Us",
        "The Hunger Games",
        "Daisy Jones & The Six",
        "The Fault in Our Stars",
        "A Court of Thorns and Roses",
        "The Catcher in the Rye",
        "We Were Liars",
        "Looking for Alaska",
        "They Both Die at the End",
        "The Invisible Life of Addie LaRue",
        "Eleanor & Park",
        "Red, White & Royal Blue",
        "All the Bright Places",
        "Ugly Love",
        "Paper Towns",
        "Verity",
        "Before I Fall",
        "The Love Hypothesis",
        "Shatter Me",
    ],
    "topic": [
        "zodiac signs",
        "music taste",
        "weird dreams",
        "deep fears",
        "the future",
        "unpopular opinions",
        "random 'what ifs'",
        "favorite childhood shows",
        "relationship red flags",
        "how aliens probably exist",
        "dream travel plans",
        "how social media messes us up",
        "the difference between alone and lonely",
        "our generation’s obsession with nostalgia",
        "vibes vs. logic",
        "the idea of soulmates",
        "high school drama",
        "cancel culture",
        "core memories",
    ],
    "quote": [
        "you’re not stuck, you’re just scared",
        "everything happens for a reason",
        "this too shall pass",
        "it's okay to outgrow people",
        "feel the fear and do it anyway",
        "you become what you believe",
        "protect your peace",
        "vibes speak louder than words",
        "don't text your ex",
        "healing isn’t linear",
        "energy never lies",
        "be so real they feel it",
        "your past doesn’t define you",
        "stay soft but don’t take nonsense",
        "you are not too much",
        "what’s meant for you won’t miss you",
        "the universe always listens",
        "don’t shrink to fit someone’s vibe",
        "your weird is your power",
    ],
    "character": [
        "Wednesday Addams",
        "Peter Parker",
        "Katniss Everdeen",
        "Rory Gilmore",
        "Damon Salvatore",
        "Miles Morales",
        "Chandler Bing",
        "Rue Bennett",
        "Luna Lovegood",
        "Joe Goldberg",
        "Elliot from Euphoria",
        "Coraline",
        "Jake Peralta",
        "Blair Waldorf",
        "Fezco",
        "Geralt of Rivia",
        "Mabel Pines",
        "Veronica Lodge",
        "Steve Harrington",
        "Nico di Angelo",
    ],
    "symbol": [
        "a broken heart",
        "a flame",
        "an infinity sign",
        "a butterfly",
        "a lock and key",
        "a wave",
        "a moon phase",
        "angel numbers",
        "a skull",
        "a compass",
        "a paper airplane",
        "a star",
        "a lightning bolt",
        "a phoenix",
        "a third eye",
        "a dagger",
        "a rose",
        "a clock",
        "a mirror",
        "a falling feather",
    ],
    "relationship_type": [
        "a situationship",
        "a summer fling",
        "a slow-burn romance",
        "a messy breakup",
        "a crush with no closure",
        "a friends-to-lovers story",
        "a 'right person, wrong time' deal",
        "a one-sided thing",
        "a real connection",
        "a rebound that got too real",
        "an unexpected spark",
        "an almost-love",
        "an accidental heartbreak",
        "a toxic loop",
        "a high school cliché",
        "a deep situationship that felt like more",
        "a Snapchat streak turned serious",
        "a 'we never dated but it still hurt'",
        "a vibe that couldn’t last",
        "a rollercoaster you couldn’t leave",
    ],
    "story": [
        "how I fell apart and rebuilt better",
        "a secret I never told anyone",
        "something that changed me forever",
        "the time I felt truly seen",
        "how we went from strangers to almost something",
        "my biggest plot twist",
        "the memory I can’t shake",
        "how I lost and found myself",
        "the mess I needed to grow",
        "the night everything made sense",
        "a moment I didn’t know was goodbye",
        "a text that changed everything",
        "the call I almost didn’t answer",
        "the version of me I left behind",
        "how we laughed before it all fell apart",
        "something small that meant everything",
        "how the silence said more than words",
        "the playlist that got me through it",
        "a mistake I secretly don’t regret",
        "how I became someone new",
    ],
    "fun_fact": [
        "octopuses have three hearts and they all break at once",
        "some turtles can breathe through their butts",
        "bananas are actually berries, but strawberries aren’t",
        "your brain literally rewires when you fall in love",
        "goosebumps are a leftover defense from our cave days",
        "you technically glow in the dark, just not enough to see",
        "cats can make over 100 different sounds",
        "sharks existed before trees did",
        "laughing for 15 minutes burns around 40 calories",
        "you start to recognize faces at just a few days old",
        "sea otters hold hands when they sleep so they don’t float away",
        "the Eiffel Tower gets taller in the summer",
        "you forget dreams within 5 minutes of waking up",
        "a bolt of lightning is five times hotter than the sun",
        "some people have a gene that lets them smell ants",
        "you’re taller in the morning than at night",
        "the heart can sync its rhythm with someone you're emotionally close to",
        "cows have best friends and get stressed when they're separated",
        "your stomach gets a new lining every 3–4 days",
        "the moon has moonquakes, just like earthquakes but quieter",
    ],
    "sex_topic": [
        "first times",
        "hookups",
        "awkward moans",
        "losing it",
        "late night texts",
        "morning afters",
        "friends with benefits",
        "sneaky links",
        "sexting gone wrong",
        "timing",
        "regrets",
        "random cravings",
        "the heat of the moment",
        "Netflix and chill",
        "accidental nudes",
        "safety talks",
        "birth control convos",
        "mixed signals",
    ],
    "body_part": [
        "lips",
        "neck",
        "collarbone",
        "thighs",
        "hips",
        "eyes",
        "waist",
        "hands",
        "fingers",
        "shoulders",
        "legs",
        "arms",
        "cheeks",
        "back",
        "chest",
        "ears",
        "jawline",
    ],
    "teacher": [
        "Mr. Thompson",
        "Ms. Ramirez",
        "Coach D",
        "Mrs. Patel",
        "Mr. Li",
        "Dr. K",
        "Mr. Bennett",
        "Ms. Allen",
        "Mr. Blake",
        "Mrs. Gomez",
        "Coach T",
        "Mrs. N",
        "Mr. H",
        "Miss J",
    ],
    "subject": [
        "math",
        "English",
        "biology",
        "history",
        "chemistry",
        "physics",
        "gym",
        "art",
        "music",
        "economics",
        "psychology",
        "drama",
        "Spanish",
        "computer science",
    ],
    "crush": [
        "my lab partner",
        "the senior with the hoodie",
        "my best friend's sibling",
        "the quiet kid in third period",
        "my ex's friend",
        "the cheerleader",
        "the goalie",
        "someone I shouldn't like",
        "the kid with the messy hair",
        "that skater boy",
        "the girl who always smells like vanilla",
        "the one who sits behind me",
    ],
    "substance": [
        "caffeine",
        "sugar",
        "vape clouds",
        "preworkout",
        "soda",
        "bubble tea",
        "energy drinks",
        "nicotine",
        "weed",
        "cough syrup",
        "junk food",
    ],
    "drug": [
        "edibles",
        "vape pens",
        "Xanax",
        "shrooms",
        "weed",
        "molly",
        "acid",
        "Adderall",
        "lean",
        "dab pens",
        "CBD",
        "LSD",
        "Zyn",
        "THC gummies",
    ],
    "excuse": [
        "my Wi-Fi glitched",
        "my dog ate it",
        "I thought it was due tomorrow",
        "I wasn’t feeling well",
        "I had practice",
        "I forgot",
        "my alarm didn’t go off",
        "I was grounded",
        "I had family stuff",
        "my laptop died",
        "Google Docs crashed",
        "I submitted it but it didn’t go through",
    ],
    "person": [
        "my best friend",
        "my ex",
        "my cousin",
        "my mom",
        "my crush",
        "my sibling",
        "the school counselor",
        "the drama queen",
        "the class clown",
        "my coach",
        "my ride or die",
        "the annoying group chat leader",
    ],
    "situation": [
        "walking in late",
        "failing a test",
        "saying the wrong name",
        "texting the wrong person",
        "leaving them on read",
        "getting caught lying",
        "drunk calling someone",
        "accidentally posting a story",
        "sneaking out",
        "getting ghosted",
        "crying at school",
        "throwing up at the party",
        "getting caught cheating",
        "spilling tea accidentally",
    ],
}
